plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', include: ['*.jar'])
}

javafx {
    version = "21"
    modules = ['javafx.controls', 'javafx.graphics', 'javafx.fxml']
}

application {
    mainClass = 'frontend.BeautyMatchApp'
}

run {
    standardInput = System.in
}
